version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - laravel

  # MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: car
      MYSQL_USER: paulo
      MYSQL_PASSWORD: paulo
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - laravel

  # Adminer Service
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-db:
    driver: local
